name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage
          pip install flask
          pip install flask-wtf
          pip install flask-sqlalchemy
          pip install email-validator
          pip install flask_behind_proxy
          pip install flask_login
          pip install GitPython
          pip install openai

      - name: Test with unittest
        run: python3 -m unittest test.py
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          
      - name: Check code coverage
        run: |
          python3 -m coverage run -m unittest test.py
          python3 -m coverage report
          python3 -m coverage html
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          
    #   - name: Archive code coverage HTML report
    #     uses: actions/upload-artifact@v2
    #     with:
    #        name: code-coverage-report
    #        path: htmlcov